class ChangeTypeOfYearFulldataset < ActiveRecord::Migration
  def change
  	change_column :fulldatasets, :year1990, 'float USING CAST(year1990 AS float)'
  	change_column :fulldatasets, :year1991, 'float USING CAST(year1991 AS float)'
  	change_column :fulldatasets, :year1992, 'float USING CAST(year1992 AS float)'
  	change_column :fulldatasets, :year1993, 'float USING CAST(year1993 AS float)'
  	change_column :fulldatasets, :year1994, 'float USING CAST(year1994 AS float)'
  	change_column :fulldatasets, :year1995, 'float USING CAST(year1995 AS float)'
  	change_column :fulldatasets, :year1995, 'float USING CAST(year1996 AS float)'
  	change_column :fulldatasets, :year1997, 'float USING CAST(year1997 AS float)'
  	change_column :fulldatasets, :year1998, 'float USING CAST(year1998 AS float)'
  	change_column :fulldatasets, :year1999, 'float USING CAST(year1999 AS float)'
  	change_column :fulldatasets, :year2000, 'float USING CAST(year2000 AS float)'
  	change_column :fulldatasets, :year2001, 'float USING CAST(year2001 AS float)'
  	change_column :fulldatasets, :year2002, 'float USING CAST(year2002 AS float)'
  	change_column :fulldatasets, :year2003, 'float USING CAST(year2003 AS float)'
  	change_column :fulldatasets, :year2004, 'float USING CAST(year2004 AS float)'
  	change_column :fulldatasets, :year2005, 'float USING CAST(year2005 AS float)'
  	change_column :fulldatasets, :year2006, 'float USING CAST(year2006 AS float)'
  	change_column :fulldatasets, :year2007, 'float USING CAST(year2007 AS float)'
  	change_column :fulldatasets, :year2008, 'float USING CAST(year2008 AS float)'
  	change_column :fulldatasets, :year2009, 'float USING CAST(year2009 AS float)'
  	change_column :fulldatasets, :year2010, 'float USING CAST(year2011 AS float)'
  	change_column :fulldatasets, :year2011, 'float USING CAST(year2011 AS float)'
  	change_column :fulldatasets, :year2012, 'float USING CAST(year2011 AS float)'
  	change_column :fulldatasets, :year2013, 'float USING CAST(year2011 AS float)'
  	change_column :fulldatasets, :year2014, 'float USING CAST(year2011 AS float)'
  	change_column :fulldatasets, :year2015, 'float USING CAST(year2011 AS float)'
  end
end
